package com.proitbridge.lms.service.storage;

import java.io.InputStream;

/**
 * Where bytes live.
 *
 * Nothing else in the application knows. Every document holds a fileId, every download
 * goes through FileService, and FileService goes through here. So moving from a disk to
 * object storage is one new class and a config line, not a change that reaches the rest
 * of the codebase.
 *
 * The key is opaque and generated by FileService: never a filename, never guessable, and
 * never anything a caller can influence. An implementation stores exactly what it is
 * given under exactly that key.
 */
public interface StorageProvider {

    String key();

    void put(String storageKey, InputStream data, long sizeBytes, String contentType);

    byte[] get(String storageKey);

    void delete(String storageKey);

    /**
     * True when the provider can hand the browser a short lived URL of its own. Object
     * storage can, which takes large downloads off the API entirely; a disk cannot, so
     * FileService streams the bytes instead.
     */
    default boolean supportsDirectUrl() { return false; }

    default String directUrl(String storageKey, String filename, int seconds) {
        throw new UnsupportedOperationException("This provider cannot sign URLs.");
    }
}
